### PR TITLE
Update utilities

### PR DESCRIPTION
**Pull request by twpayne**
This PR updates the list of dotfile managers, updates a description, and prioritizes repos hosted on GitHub over legacy repos.

### CODE REVIEW

**Comment by twpayne** [comment]
The CI failure ("The command "find _site -name '*.html' | xargs awesome_bot --allow-dupe --allow-redirect" exited with 123.") seems unrelated to this PR.

**Comment by anishathalye** [comment]
I've fixed CI in https://github.com/dotfiles/dotfiles.github.com/pull/284. Perhaps this patch should be edited to only include the manual changes to create a minimal diff?

**Comment by twpayne** [comment]
> Perhaps this patch should be edited to only include the manual changes to create a minimal diff?

Thanks, will do. Let's get #284 merged first to reduce conflicts. Once #284 is in then I'll update this PR.

**Comment by twpayne** [comment]
Closing in favor of #285. I'll update chezmoi's description once #284 is merged.

**Pull request closed without merging**
