### PR TITLE
Update 2KAbhishek's Dotfiles section

### PR DESCRIPTION
**Pull request by 2KAbhishek**
# Description

My dotfiles have changed a lot since the time I had last added them here, I wanted to update the link and also include some other extenstions for it here.

# Copyright Assignment

- [x] This document is covered by the [MIT License](https://github.com/dotfiles/dotfiles.github.com/blob/master/LICENSE.md), and I agree to contribute this PR under the terms of the license.

### CODE REVIEW

**Comment by 2KAbhishek** [comment]
@unixorn looks like an unrelated check is failing here, can you please help 🙏🏽

**Comment by 2KAbhishek** [comment]
Hi @unixorn will it be possible to get this merged soon? please let me know if I can help, or if any changes are needed

**Comment by unixorn** [comment]
Sorry, I've been busy and somehow missed this notification

**Review by unixorn — APPROVED** [review]
lgtm

**Pull request merged**
