### PR TITLE
Add BachoSeven's dotfiles

### PR DESCRIPTION
**Pull request by BachoSeven**
thanks:)

### CODE REVIEW

**Comment by BachoSeven** [comment]
@unixorn Just pinging you since I saw https://github.com/dotfiles/dotfiles.github.com/pull/306#issuecomment-928465946

**Comment by unixorn** [comment]
Thanks for the ping. I maintain [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) and that generates a ton of notifications that flood out my inbox sometimes.

**Comment by BachoSeven** [comment]
I should have fixed the tests - there was a `:` in the description.

**Review by unixorn — APPROVED** [review]
LGTM

**Comment by unixorn** [comment]
np, that's what the tests are for.

**Comment by unixorn** [comment]
Thanks for the contribution!

**Pull request merged**
