### PR TITLE
Jekyll

### LINKED ISSUE #62: Compile with GitHub pages
There has been a lot of work done on GitHub pages since this was originally set up. I could take a crack at making it work without the pre-compile stage.

### LINKED ISSUE #97: Missing LICENCE file
http://choosealicense.com/

MIT?

### PR DESCRIPTION
**Pull request by twe4ked**
Hi :)

This PR converts the current nanoc site to a GitHub Pages compatible Jekyll site. The benefit of using a Jekyll site is we no longer need to maintain a source and master branch as GitHub Pages will do the compiling for us. It also simplifies quite a bit of configuration.

#### Other Minor Changes

- The ./script/console script was removed as it's no longer necessary, there is no lib file to require
- I've removed a reference to a non-existent LICENCE file and opened a related issue (#97)
- Other minor README tweaks

I'm not sure the `script/{compile,publish}` scripts are really necessary anymore either. Happy to remove them here or in another PR if you agree.

I've opened this PR against the `master` branch for GitHub pages compatibility.
See docs here: https://pages.github.com/.

Fixes #62.
Fixes #97.

### CODE REVIEW

**Comment by twe4ked** [comment]
Here is the actual change set: https://github.com/dotfiles/dotfiles.github.com/compare/fcf160195d3539f5dd0c5ffa87c1ff23a6c697a5...8fc4314e1f8d5431d2afc9f3c5a2c89ee85a7734.

**Comment by twe4ked** [comment]
Ah, I just realised the `source` branch is set as the main branch for this repo. I assumed (incorrectly) the `source` branch was the uncompiled version and the `master` branch the compiled version. What's the purpose of the `master` branch as it stands? It seems to be just a very old version of the `source` branch.

Is anything still happening with the `feature/blog` branch? It looks like there is a single unpublished blog post there. Using Jekyll will allow a blog to be added on easily if there is someone to keep it updated.

I can recreate this PR against the `source` branch if there is a reason to keep it off master.

**Comment by unixorn** [comment]
The source branch is the uncompiled content. Master is what is actually served as the website. Once I merge changes to source, I do `script/compile` to render it to the output directory, then switch to the master branch and copy the rendered files there and do another PR and merge to make the changes live on the website.

**Comment by twe4ked** [comment]
Haha, it was as I thought originally then. The “2 days ago” and “2 years ago” on the files threw me. Ignore that last comment then.

**Comment by unixorn** [comment]
This is a nice bit of work. It'll certainly make updating the site less work :-).

@pengwynn, since you own the org, do you have any thoughts on switching over to jekyll?

**Comment by pengwynn** [comment]
+:100: on switching to Jekyll. :sparkles:

Feel free to prune any scripts that are now obsolete. Even though some server magic happens, I'd keep the ones that make local development nicer.

> Is anything still happening with the feature/blog branch? 

No, it's dead.

**Comment by unixorn** [comment]
@twe4ked Once you're happy with the PR and it merges cleanly, I'll pull the trigger and commit. This was a bunch of work that will make updates a lot easier, thank you for the contribution.

**Comment by twe4ked** [comment]
Can you guys just push my branch over the master branch. I tried doing a rebase but there are tons of merge conflicts as the branches are completely different. I've added the `LICENCE.md` file from the `master` branch too.

**Comment by twe4ked** [comment]
I took another look at the `feature/blog` branch and the post is on [The Changelog](https://thechangelog.com/using-imageoptim-with-guard-shell/) as I'm sure you know so it can definitely be deleted.

**Comment by twe4ked** [comment]
Any chance of getting this merged before we get more PRs? I'm happy to fix #99 after the merge.

**Comment by unixorn** [comment]
@twe4ked, sorry it took so long for me to get this merged, I was busy offline. I've resolved the merge conflicts from this PR in #100 which closes this.

Thanks for the contribution, it will make maintaining the site a lot easier.

@pengwynn, would you please reset the default branch from source to master? Thanks!

**Comment by pengwynn** [comment]
@unixorn Done!

**Comment by twe4ked** [comment]
@unixorn No worries, thanks for doing the merge.

**Pull request merged**
