### PR TITLE
Refactor website

### LINKED ISSUE #257: Refactor: reorganize, split into pages, and order by notability
This seems to be a very popular resource (the first result on Google when searching "dotfiles"). That's pretty awesome!

I think in its current state, the page has grown to a size where it is tough to navigate. See related issues #186 and #207.

In my opinion, some content could be removed, and the content overall could be organized better so that it is easier to navigate. I'm suggesting the following concrete changes:

### 1. Reorganize topics

I'd propose the following topic order and hierarchy. (The exact wording of the topic names can be tweaked.)

1. Tutorials
2. General-purpose dotfile utilities
3. Tool-specific frameworks
4. Bootstrap repositories
5. Dotfiles repositories for inspiration
6. Miscellaneous
7. FAQ

For some of the topics above, it's clear how the existing topics map over. I think this order better reflects the order in which new users should navigate the material.

In the hierarchy above, I've split the current "go further with a framework" into two top-level headings, separating the general-purpose utilities and following with the tool-specific stuff for shells/editors/etc.

I've also split "get started with a bootstrap" into two categories. Right now, the list contains various users' dotfiles (e.g. [Abdullah's dotfiles](https://gitlab.com/Abdullah/cfg.git) are the first link on the entire page), most of which are not necessarily meant for others to build on top of. On the other hand, things like [dotphiles](https://github.com/dotphiles/dotphiles) look like they're actually meant as a bootstrap. I think the former can go into a "inspiration" section, whereas the bootstrap repositories can stay in a dedicated bootstrap section. The current bootstrap list also contains things like [Awesome dotfiles](https://github.com/webpro/awesome-dotfiles), which is not a bootstrap repository; I propose things like this are moved to the Miscellaneous section. It also contains things like [bashdot](https://github.com/bashdot/bashdot), which should be moved to the general-purpose dotfiles utilities section.

The miscellaneous section can contain everything that doesn't fit in any other category. This includes the current "tips and tricks" style content, like "don't ignore your .gitignore" and "embrace submodules / subtrees".

### 2. Split content across pages

I think the site is kind of intimidating and hard to navigate. I'd be in favor of splitting major topics across pages, and then adding some sort of navigation to go between the pages.

### 3. Write a brief intro for the homepage

With content split across pages, the homepage can have a brief text that introduces the user to the site and summarizes the idea of dotfiles management.

### 4. Remove some content

It might be nice to introduce some sort of notability criteria, e.g. as Homebrew [does](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md). I think their current criteria is (>= 20 forks OR >= 20 watchers OR >= 50 stars), but we could come up with our own.

This will help cut down on the overwhelming quantity of content on the site, and help navigate users to high quality projects rather than leaving it to chance which of the 1000 links they click on.

Stars/watchers/forks are a very rough proxy for the quality of a project, but I can't think of better alternatives.

### 5. Order existing content based on notability

Even with a notability criteria, I'd say it's worth ordering content based on a better metric than alphabetical order. Not to pick on this person in particular, but currently [Abdullah's dotfiles](https://gitlab.com/Abdullah/cfg.git) (6 stars) are currently the first link on the page. Arguably, this is a less useful resource than e.g. [Zach Holman's dotfiles](https://github.com/holman/dotfiles) (5.6k stars), which are currently buried deep in the "get started with a bootstrap section".

Sorting each of the topics based on stars helps solve this problem. Again, stars aren't the best metric, but I don't think there's a great alternative (and stars are better than alphabetical order!).

Another metric we could consider is number of users, but that might be hard to measure for certain frameworks. E.g. measuring it for Pathogen might be easy by analyzing public dotfiles repos on GitHub (because you can tell from vimrc contents), but measuring it for a program like stow might be hard, because you install the program on your machine to manage dotfiles, and it can't necessarily be deduced that someone's using stow from the contents of their dotfiles repo.

---

What are people's thoughts on this proposed reorganization? (cc @bedge @sparr, since they opened similar issues) And what do the maintainers think of this? (cc @unixorn)

If people are in favor of these changes, I'd be happy to do the implementation work.

### PR DESCRIPTION
**Pull request by anishathalye**
The single-page website has grown to a size where it's tough to navigate. See https://github.com/dotfiles/dotfiles.github.com/issues/186 and https://github.com/dotfiles/dotfiles.github.com/issues/207.

This patch fixes #257. In particular, this patch:

- Reorganizes topics (see sidebar)
- Splits content across pages
- Includes a brief introduction on the homepage
- Introduces a notability criteria and removes non-notable content
- Orders existing content based on notability/popularity

This patch aims to minimize changes to website content: it is mostly adapting content from the old site into the new organization.

You can of course test this out on your own machine, but if anyone wants to quickly preview it, [here is a demo](https://d.anish.io/).

### CODE REVIEW

**Comment by anishathalye** [comment]
(I don't think GitHub automatically messages people when a pull request is referenced (257), so tagging relevant people here: @TheLocehiliosan @bedge @neeasade; no tags for pengwynn and unixorn cause they probably got an email for the pull request)

So here's a draft pull request. A couple things that might be useful to discuss:

- What should the notability criteria be? I [chose one](https://github.com/anishathalye/dotfiles.github.com/blob/refactor/CONTRIBUTING.md#notability-criteria) somewhat arbitrarily, but I think it works out well -- the amount of information on the pages seems manageable now.
- Do the page links in the sidebar look okay? I think it's a bit ugly and should probably be tweaked a bit before this is actually merged. The underline for the active page is ugly, and the sidebar doesn't look good on mobile.
- Can we get rid of the "tips and tricks" + "FAQ" pages? In this PR, I tried to make minimal edits to actual content and only do reorganization. But I think those pages feel a bit out of place, giving some very specific advice that's probably covered by tutorials (or people can google those issues when they come up).
- Is the content on the homepage reasonable? (the "navigating this site") Other than that, the homepage is now pretty devoid of content. I think this is fine though? (Not sure what other content we might want to put there with the new organization).

Other more minor things:

- Can we remove the Twitter stuff from the sidebar? That account doesn't seem active anymore (last tweet was in 2013).
- Similarly, is the Gauges link necessary?

**Comment by unixorn** [comment]
Yes, remove the twitter account. I also don't think the gauges link is necessary either.

**Comment by anishathalye** [comment]
No worries. Rebased onto master and made sure to include that latest merge (14fd7c7).

**Comment by unixorn** [comment]
Thanks to your work the site is more usable now. Thanks for the contribution.

**Pull request merged**
