### PR TITLE
Added jh3y's kody to bootstraps

### PR DESCRIPTION
**Pull request by jh3y**
Added my personal node bootstrapping tool to the list of bootstraps.

@jh3y

### CODE REVIEW

**Comment by unixorn** [comment]
Thanks for the contribution!

**Comment by jh3y** [comment]
Thanks @unixorn ,

When might this get merged into `master`?

Contributing guidelines suggested PRs to the source branch but I have noticed some of the other PRs are straight to master.

@jh3y

**Comment by unixorn** [comment]
We recently switched to using the master branch, thanks for pointing out that we haven't updated the contributing guidelines.

**Comment by unixorn** [comment]
Added #107

**Comment by e1b2i3** [comment]
nice

**Pull request merged**
