### PR TITLE
✨Add thuanpham2311's dotfiles

### PR DESCRIPTION
**Pull request by thuanpham2311**
:smile: Have a good day

### CODE REVIEW

**Comment by unixorn** [comment]
This PR removes a couple of images from the images directory. Once that is reverted, it's good to merge.

**Comment by thuanpham2311** [comment]
> This PR removes a couple of images from the images directory. Once that is reverted, it's good to merge.

Thank 😃, I'm updated

**Review by unixorn — APPROVED** [review]
LGTM

**Comment by unixorn** [comment]
Thanks for the contribution!

**Pull request merged**
