### PR TITLE
Update Gemfile to the latest versions

### PR DESCRIPTION
**Pull request by d2s**
- Update `Gemfile` to the latest versions of required gems
- Related to the #162 issue (_`bundle install` fails to work_)

More details:
- https://github.com/dotfiles/dotfiles.github.com/issues/162

### CODE REVIEW

**Comment by unixorn** [comment]
Thanks!

**Comment by greysteil** [comment]
Would you be up for automating the dependency updates? I built [Dependabot](https://dependabot.com) to automatically create PRs like this one and keep everything up-to-date. (Obviously totally free.)

**Comment by unixorn** [comment]
I'm open to it. This repo doesn't get a ton of activity so it is easy for it to get stale.

**Comment by greysteil** [comment]
Sweet! If you go for Dependabot then it's a GitHub app, so you need to click through the auth process and then click to add this repo as a project. Hopefully all obvious but let me know any feedback.

Here's an [example](https://github.com/greysteil/ossfriday/pull/10) of the PRs it generates.

**Pull request merged**
